import { MathJaxContext } from "better-react-mathjax";
import type { Metadata } from "next";
import "github-markdown-css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mathJaxConfig = {
  loader: { load: ['[tex]/ams'] },
  tex: {
    packages: { '[+]': ['ams'] },
    inlineMath: [['$', '$'], ['\\(', '\\)']],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, width: "100vw", height: "100vh" }}>
        <MathJaxContext config={mathJaxConfig}>
          <div className="markdown-body">
            {children}
          </div>
        </MathJaxContext>
      </body>
    </html >
  );
}
